### ISSUE TITLE
Error in laplace smoothing 

### ISSUE THREAD

**Issue by prince5844** [sumilk/BITS_ML#1]
![naive](https://user-images.githubusercontent.com/24958819/213788583-cd126d51-cd57-4234-b82d-97b68575714b.JPG)

question detail:- Given the following labelled training data,
Flat 20% Cashback on Oyo Room bookings done via Paytm. (SPAM)
Lets Talk Fashion! Get flat 40% Cashback on Backpacks (SPAM)
Opportunity with Product firm for Fullstack (HAM)
Javascript Developer, Full Stack Developer in Bangalore (HAM)
Use Naive Bayes Classifier with laplace smoothing to identify classification of the sentence “Scan
Paytm QR Code to Pay & Win 100% Cashback”

**Comment by sumilk** [comment]
resolved
